[workspace]
resolver = "2"
members = ["mcmpmgr", "mmm"]

[workspace.package]
authors = ["Warren Hood <nullbyte001@gmail.com>"]
version = "0.2.1"
edition = "2021"

[workspace.metadata.crane]
name = "mcmpmgr-workspace"
